name: Release & Upload to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    uses: cameronabrams/workflows/.github/workflows/python-release.yml@main
    with:
      rtd_slug: ycleptic
      run_tests: true
    secrets: inherit

  publish:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
