name: Release & Upload to PyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    uses: cameronabrams/workflows/.github/workflows/python-release.yml@main
    with:
      rtd_slug: ycleptic
      run_tests: true
      use_api_token: true
    secrets: inherit
